apiVersion: v1
kind: Secret
metadata:
  name: headlamp-readonly-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: headlamp-readonly
type: kubernetes.io/service-account-token
